#
# MAINTAINER        Moji,nosix <six.heyaxiang@gmail.com>
# DOCKER-VERSION    1.6.2
#
# Dockerizing CentOS7: Dockerfile for building CentOS images
#
FROM       registry
MAINTAINER Moji,nosix <six.heyaxiang@gmail.com>

EXPOSE 5000

